image: tetraweb/php

variables:
  S3_BUCKET_NAME: "shaun-clift"

before_script:
  - npm install
  - npm run build

deploy:
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp ./dist/ s3://$S3_BUCKET_NAME/ --recursive